import React, { useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { ArrowRight, ChevronDown, Heart, Menu, Search, ShoppingBag, Truck, X } from 'lucide-react'
import './styles.css'

const company = { name: '俊锦贸易有限公司', email: 'junjinshop@outlook.com', address: 'Room 2209, 22/F, Convention Plaza Office Tower, 1 Harbour Road, Wan Chai, Hong Kong' }
const media = {
  furniture: '/assets/furniture.webp', soft: '/assets/soft-furnishings.webp', essentials: '/assets/essentials.webp', decor: '/assets/decor-lighting.webp', kitchen: '/assets/kitchen-bath.webp'
}
const groups = [
  { id: 'furniture', label: 'Furniture', eyebrow: '01 / living well', intro: 'Grounded silhouettes and everyday pieces, designed to settle beautifully into your home.', names: ['Boucle Sofa','Walnut Bed','Oak Wardrobe','Dining Table','Round Coffee Table','Low TV Console','Six-Drawer Dresser','Oak Sideboard','Open Bookcase','Writing Desk','Lounge Chair','Dining Chair','Vanity Table','Bedside Table','Shoe Cabinet'] },
  { id: 'soft', label: 'Soft Furnishings', eyebrow: '02 / soft layers', intro: 'Quiet textures, natural tones and soft layers for rooms that feel lived in.', names: ['Linen Curtains','Woven Rug','Neutral Cushion','Framed Wall Art','Potted Green Plant','Sheer Curtains','Wooden Blinds','Textured Wallcovering','Woven Tapestry','Lumbar Pillow','Seat Cushion','Artificial Flower Arrangement','Folding Room Divider','Striped Throw Blanket','Boucle Bolster'] },
  { id: 'essentials', label: 'Home Essentials', eyebrow: '03 / daily rituals', intro: 'Useful, tactile pieces that bring a little more order and comfort to each day.', names: ['Four-Piece Bedding Set','Fabric Storage Box','Woven Floor Mat','Folded Duvet','Cloud Pillow','Fitted Sheet','Cotton Bath Towel','Cotton Bathrobe','Laundry Basket','Lidded Storage Bin','Fabric Storage Bag','Wooden Hangers','Fabric Dust Cover','Tissue Box Cover','House Slippers'] },
  { id: 'decor', label: 'Decor & Lighting', eyebrow: '04 / small atmosphere', intro: 'Warm light and sculptural details that change the feeling of a room.', names: ['Amber Reed Diffuser','Pleated Table Lamp','Linen Floor Lamp','Brass Wall Sconce','Minimal Desk Clock','Decor Frame','Sculptural Candle Holder','Abstract Wood Sculpture','Paper Lantern','Brass Pendant Lamp','Woven Basket Decor','Felt Pinboard','Wooden Tray','Dried Botanical Arrangement','Fabric Lampshade'] },
  { id: 'kitchen', label: 'Kitchen & Bath', eyebrow: '05 / considered utility', intro: 'Calm, durable accessories for the kitchen and bath, made for everyday use.', names: ['Linen Placemat','Cotton Tablecloth','Quilted Heat Mat','Wooden Kitchen Rack','Fabric Shower Curtain','Rubber Bath Mat','Matte Black Towel Rack','Bamboo Bathroom Shelf','Fabric Toiletry Organizer','Wooden Dish Rack','Cotton Napkin Set','Woven Bread Basket','Fabric Bath Caddy','Bamboo Laundry Shelf','Countertop Organizer'] }
]
const prices = [189,249,279,229,89,159,199,219,179,149,129,79,169,99,119, 39,89,49,69,59,45,79,119,99,39,29,44,69,55,35, 129,49,39,79,69,55,29,89,59,65,45,39,35,29,25, 28,79,119,69,39,89,49,79,59,99,45,35,29,55,69, 19,39,25,89,49,39,59,79,45,69,29,35,49,89,59]
const slug = s => s.toLowerCase().replace(/[^a-z0-9]+/g, '-')
const products = groups.flatMap((group, gi) => group.names.map((name, index) => ({ id: `${group.id}-${index}`, name, category: group.label, group: group.id, price: prices[gi * 15 + index], image: media[group.id], cell: index, badge: index === 0 ? 'New season' : index === 4 ? 'Bestseller' : '' })))

function ProductImage({ product, large = false }) { const col = product.cell % 3; const row = Math.floor(product.cell / 3); return <div className={`product-image ${large ? 'large' : ''}`} style={{ backgroundImage: `url(${product.image})`, backgroundPosition: `${col * 50}% ${row * 25}%` }}><span className="image-number">{String(product.cell + 1).padStart(2, '0')}</span></div> }

function App() {
  const [route, setRoute] = useState(window.location.hash.replace('#', '') || 'home')
  const [active, setActive] = useState('all'); const [cart, setCart] = useState([]); const [drawer, setDrawer] = useState(false); const [menu, setMenu] = useState(false)
  const go = r => { window.location.hash = r; setRoute(r); window.scrollTo({ top: 0, behavior: 'smooth' }); setMenu(false) }
  const add = (p, buy = false) => { setCart(items => [...items, p]); buy ? go('checkout') : setDrawer(true) }
  const filtered = useMemo(() => active === 'all' ? products : products.filter(p => p.group === active), [active])
  if (route === 'checkout') return <Checkout cart={cart} go={go} />
  if (route === 'admin') return <Admin go={go} />
  if (route !== 'home' && route !== 'shop') return <Policy route={route} go={go} />
  return <div className="site-shell"><header className="header"><button className="icon-button menu-button" onClick={() => setMenu(!menu)} aria-label="Menu"><Menu size={21}/></button><button className="wordmark" onClick={() => go('home')}>JUNJIN<span>HOME</span></button><nav className={`nav ${menu ? 'open' : ''}`}><button onClick={() => go('home')}>Home</button><button onClick={() => go('shop')}>Shop</button>{groups.map(g => <button key={g.id} onClick={() => { setActive(g.id); go('shop') }}>{g.label}</button>)}</nav><div className="header-actions"><button className="icon-button" aria-label="Search"><Search size={19}/></button><button className="bag-button" onClick={() => setDrawer(true)}><ShoppingBag size={19}/><b>{cart.length}</b></button></div></header>
    {route === 'home' ? <Home go={go} setActive={setActive} add={add} /> : <Shop active={active} setActive={setActive} filtered={filtered} add={add} />}
    <Footer go={go} />{drawer && <CartDrawer cart={cart} close={() => setDrawer(false)} go={go} />}</div>
}

function Home({ go, setActive, add }) { const hero = products[0]; return <main><section className="hero"><div className="hero-copy"><p className="kicker">JUNJIN HOME / 2026 COLLECTION</p><h1>A softer way<br/>to live <em>well.</em></h1><p className="hero-text">A considered edit of furniture, objects and everyday comforts — made for the spaces and rituals that are uniquely yours.</p><button className="dark-button" onClick={() => go('shop')}>Explore the collection <ArrowRight size={17}/></button></div><div className="hero-art"><ProductImage product={hero} large/><div className="hero-caption"><span>01 / signature pieces</span><strong>Warm wood · calm forms</strong></div></div></section><section className="marquee"><span>Thoughtful living</span><span>•</span><span>Quietly made</span><span>•</span><span>Daily beauty</span><span>•</span><span>Thoughtful living</span></section><section className="category-section"><div className="section-heading"><div><p className="kicker">SHOP BY MOOD</p><h2>Make room for <em>more.</em></h2></div><button className="text-button" onClick={() => go('shop')}>View all products <ArrowRight size={16}/></button></div><div className="category-grid">{groups.map((g, i) => <button className="category-card" key={g.id} onClick={() => { setActive(g.id); go('shop') }}><div className="category-art" style={{ backgroundImage: `url(${media[g.id]})`, backgroundPosition: '0% 0%' }}><span>0{i + 1}</span></div><div><small>{g.eyebrow}</small><h3>{g.label}</h3></div></button>)}</div></section><section className="feature"><div className="feature-copy"><p className="kicker">THE EVERYDAY EDIT</p><h2>Objects with<br/><em>a point of view.</em></h2><p>We look for the honest grain of wood, the hand-feel of linen, the glow of a warm bulb. Pieces chosen to live alongside you, not compete for attention.</p><button className="outline-button" onClick={() => go('about')}>Our approach <ArrowRight size={16}/></button></div><div className="feature-card"><ProductImage product={products[46]} large/><div className="feature-label"><span>New light</span><strong>Pleated Table Lamp · $79</strong></div></div></section><section className="newsletter"><p className="kicker">A NOTE FROM JUNJIN</p><h2>Good things, <em>in your inbox.</em></h2><p>New arrivals, home notes and quiet inspiration. No noise.</p><div className="email-row"><input placeholder="Your email address"/><button aria-label="Subscribe"><ArrowRight size={18}/></button></div></section></main> }

function Shop({ active, setActive, filtered, add }) { return <main className="shop-page"><div className="shop-intro"><p className="kicker">THE JUNJIN EDIT / {filtered.length} PIECES</p><h1>Find your <em>everyday.</em></h1><p>Furniture, soft furnishings and useful objects in a calm, collected palette.</p></div><div className="filter-row"><div className="filter-scroll"><button className={active === 'all' ? 'selected' : ''} onClick={() => setActive('all')}>All pieces</button>{groups.map(g => <button className={active === g.id ? 'selected' : ''} key={g.id} onClick={() => setActive(g.id)}>{g.label}</button>)}</div><span className="sort-label">Curated selection <ChevronDown size={15}/></span></div><div className="product-grid">{filtered.map(p => <ProductCard key={p.id} product={p} add={add}/>)}</div></main> }
function ProductCard({ product, add }) { return <article className="product-card"><div className="card-visual"><ProductImage product={product}/>{product.badge && <span className="badge">{product.badge}</span>}<button className="heart" aria-label={`Save ${product.name}`}><Heart size={17}/></button></div><div className="product-meta"><div><p>{product.category}</p><h3>{product.name}</h3></div><strong>${product.price}</strong></div><div className="product-actions"><button onClick={() => add(product)}>Add to Cart</button><button onClick={() => add(product, true)}>Buy Now - ${product.price}</button></div></article> }

function CartDrawer({ cart, close, go }) { const total = cart.reduce((s, p) => s + p.price, 0); return <><div className="drawer-backdrop" onClick={close}/><aside className="cart-drawer"><div className="drawer-head"><div><p className="kicker">YOUR BAG</p><h2>{cart.length} {cart.length === 1 ? 'piece' : 'pieces'}</h2></div><button className="icon-button" onClick={close}><X size={20}/></button></div>{cart.length === 0 ? <div className="empty-cart"><ShoppingBag size={28}/><p>Your bag is waiting for something good.</p></div> : <><div className="cart-items">{cart.map((p, i) => <div className="cart-item" key={`${p.id}-${i}`}><ProductImage product={p}/><div><h3>{p.name}</h3><p>${p.price}</p></div></div>)}</div><div className="cart-total"><span>Subtotal</span><strong>${total}</strong></div><button className="dark-button full" onClick={() => { close(); go('checkout') }}>Continue to checkout <ArrowRight size={17}/></button><p className="drawer-note">Taxes and shipping calculated at checkout.</p></>}</aside></> }

function Checkout({ cart, go }) { const total = cart.reduce((s, p) => s + p.price, 0); return <div className="checkout-page"><header className="header"><button className="wordmark" onClick={() => go('home')}>JUNJIN<span>HOME</span></button><span className="checkout-title">Secure checkout</span><span className="secure">● encrypted demo</span></header><main className="checkout-wrap"><div><button className="back-link" onClick={() => go('shop')}>← Continue shopping</button><p className="kicker">CHECKOUT / STEP 1 OF 2</p><h1>Make it yours.</h1><div className="checkout-form"><h2>Contact & delivery</h2><div className="form-grid"><input placeholder="First name"/><input placeholder="Last name"/><input className="full-input" placeholder="Email address"/><input className="full-input" placeholder="Address"/><input placeholder="City"/><input placeholder="Postal code"/></div><h2>Payment</h2><div className="payment-options"><button className="payment selected"><span className="paypal">PayPal</span><small>Pay securely with PayPal</small></button><button className="payment"><span className="visa">VISA</span><small>Credit or debit card</small></button><button className="payment"><span className="card-symbol">▣</span><small>Credit card</small></button></div><button className="dark-button full">Place demo order <ArrowRight size={17}/></button><p className="demo-note">This is a frontend payment demo. No real payment will be processed.</p></div></div><aside className="order-summary"><p className="kicker">ORDER SUMMARY</p>{cart.length ? cart.map((p, i) => <div className="summary-item" key={`${p.id}-${i}`}><ProductImage product={p}/><div><strong>{p.name}</strong><span>${p.price}</span></div></div>) : <p>Your bag is empty. Add something from the collection.</p>}<div className="summary-total"><span>Total</span><strong>${total}</strong></div></aside></main></div> }

function Policy({ route, go }) { const content = { about: ['About Junjin','Junjin Home is a Hong Kong based home and living edit by 俊锦贸易有限公司. We choose useful, tactile pieces with a calm point of view — furniture for the long view and small objects that make ordinary rituals feel good.'], shipping: ['Shipping policy','Orders are prepared within 2–4 business days. Delivery timing and rates are shown at checkout based on destination. Tracking details are emailed when your order leaves our studio.'], tracking: ['Order tracking','Use the tracking link in your dispatch email or contact junjinshop@outlook.com with your order number. Our team will help locate your parcel.'], returns: ['Returns & refunds','Request a return within 14 days of delivery. Items must be unused and in original condition. Refunds are issued to the original payment method after inspection.'], cancellation: ['Cancellation policy','Contact us at junjinshop@outlook.com as soon as possible. Orders can be cancelled before dispatch; dispatched orders follow our returns policy.'], privacy: ['Privacy policy','We collect only information needed to process orders, provide support and improve the site. We do not sell personal information. Contact us to request access or correction.'], dmca: ['DMCA','If you believe content on this site infringes your rights, please send a notice to junjinshop@outlook.com with the relevant work, location and contact details.'], terms: ['Terms of service','These terms describe use of the Junjin Home website and our frontend shopping demonstration.'] }[route] || ['Page','']; return <div className="policy-page"><header className="header"><button className="wordmark" onClick={() => go('home')}>JUNJIN<span>HOME</span></button><button className="back-link" onClick={() => go('home')}>← Back home</button></header><main className="policy-wrap"><p className="kicker">JUNJIN HOME / INFORMATION</p><h1>{content[0]}</h1><p className="policy-lead">{content[1]}</p>{route === 'terms' && <div className="terms-list">{['Agreement to terms','Eligibility','Product information','Prices and taxes','Orders','Payment','Shipping','Delivery','Returns','Refunds','Cancellations','Intellectual property','User content','Privacy','Limitation of liability','Changes to terms','Governing law'].map((x, i) => <section key={x}><span>{String(i + 1).padStart(2, '0')}</span><div><h2>{x}</h2><p>By using Junjin Home, you agree to this section and to provide accurate information. Details are handled fairly and in line with the policies on this website.</p></div></section>)}</div>}</main><Footer go={go}/></div> }

function Footer({ go }) { return <footer className="footer"><div className="footer-main"><div><button className="wordmark light" onClick={() => go('home')}>JUNJIN<span>HOME</span></button><p className="footer-blurb">Make room for the everyday.<br/>Thoughtful objects for living well.</p></div><div className="footer-col"><h4>Explore</h4><button onClick={() => go('shop')}>Shop all</button>{groups.slice(0, 3).map(g => <button key={g.id} onClick={() => go('shop')}>{g.label}</button>)}</div><div className="footer-col"><h4>Information</h4>{[['about','About us'],['shipping','Shipping policy'],['tracking','Order tracking'],['returns','Returns & refunds'],['cancellation','Cancellation policy']].map(([r, l]) => <button key={r} onClick={() => go(r)}>{l}</button>)}</div><div className="footer-col"><h4>Legal</h4>{[['terms','Terms of service'],['privacy','Privacy policy'],['dmca','DMCA']].map(([r, l]) => <button key={r} onClick={() => go(r)}>{l}</button>)}<button onClick={() => go('admin')}>Staff admin demo</button></div></div><div className="footer-bottom"><div><strong>{company.name}</strong><span>{company.address}</span><span>{company.email}</span></div><span>© 2026 Junjin Home · All rights reserved</span></div></footer> }
function Admin({ go }) { return <div className="admin-page"><header className="header"><button className="wordmark" onClick={() => go('home')}>JUNJIN<span>HOME</span></button><button className="back-link" onClick={() => go('home')}>← Storefront</button></header><main className="admin-wrap"><p className="kicker">STAFF AREA / FRONTEND DEMO</p><h1>Good morning.</h1><div className="admin-login"><h2>Admin access</h2><input placeholder="Email" defaultValue="admin@junjinhome.com"/><input placeholder="Password" type="password" defaultValue="demo-only"/><button className="dark-button full">Sign in <ArrowRight size={17}/></button><p>Demo dashboard only — no live orders or customer data are connected.</p></div></main></div> }

createRoot(document.getElementById('root')).render(<App />)
